
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/trendvision.ai-carousel
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d3:59:44:92:fc:1c:3b:61:db:3c:1d:ac:ec:8e:4d:2d"
      - run: scp -o StrictHostKeyChecking=no -r ~/trendvision.ai-carousel/static evv@35.228.188.143:/home/evv/tv-tagger/
      - run: ssh -o StrictHostKeyChecking=no evv@35.228.188.143 sudo systemctl restart tv-tagger
workflows:
  version: 2
  build_and_test:
    jobs:
- build 
